wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.15
    is_jupyter_run: true
    python_version: 3.6.8
batch_size:
  desc: null
  value: 120.09170582129408
epochs:
  desc: null
  value: 228.72900818856442
learning_rate:
  desc: null
  value: 1.5117691615736912
